import { Injectable, Logger } from '@nestjs/common';
import ExcelJS from 'exceljs';

export interface TestCaseRow {
  externalId: string;
  module?: string | null;
  feature?: string | null;
  title: string;
  preconditions?: string | null;
  steps: unknown;
  expectedResult: string;
  priority: string;
  type: string;
  status: string;
  requirementRefs: unknown;
}

export interface ExportResult {
  buffer: Buffer;
  fileName: string;
  sizeBytes: number;
}

@Injectable()
export class ExcelExporterService {
  private readonly logger = new Logger(ExcelExporterService.name);

  async exportTestcases(
    testCases: TestCaseRow[],
    versionNo: number,
    projectName?: string,
  ): Promise<ExportResult> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'AI QA Platform';
    workbook.created = new Date();

    const sheet = workbook.addWorksheet('Test Cases', {
      pageSetup: { paperSize: 9, orientation: 'landscape' },
    });

    // ── Column definitions (§9.10 template) ─────────────────────────────
    sheet.columns = [
      { header: 'ID', key: 'externalId', width: 18 },
      { header: 'Module', key: 'module', width: 16 },
      { header: 'Feature', key: 'feature', width: 20 },
      { header: 'Title', key: 'title', width: 40 },
      { header: 'Preconditions', key: 'preconditions', width: 28 },
      { header: 'Steps', key: 'steps', width: 50 },
      { header: 'Expected Result', key: 'expectedResult', width: 36 },
      { header: 'Priority', key: 'priority', width: 12 },
      { header: 'Type', key: 'type', width: 14 },
      { header: 'Status', key: 'status', width: 14 },
      { header: 'Requirement Refs', key: 'requirementRefs', width: 24 },
    ];

    // ── Header style ─────────────────────────────────────────────────────
    const headerRow = sheet.getRow(1);
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF2563EB' },
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
      cell.border = {
        bottom: { style: 'thin', color: { argb: 'FF93C5FD' } },
      };
    });
    headerRow.height = 22;

    // ── Data rows ────────────────────────────────────────────────────────
    for (const [i, tc] of testCases.entries()) {
      const stepsText = this.stepsToText(tc.steps);
      const refsText = this.refsToText(tc.requirementRefs);

      const row = sheet.addRow({
        externalId: tc.externalId,
        module: tc.module ?? '',
        feature: tc.feature ?? '',
        title: tc.title,
        preconditions: tc.preconditions ?? '',
        steps: stepsText,
        expectedResult: tc.expectedResult,
        priority: tc.priority,
        type: tc.type,
        status: tc.status,
        requirementRefs: refsText,
      });

      row.eachCell((cell) => {
        cell.alignment = { vertical: 'top', wrapText: true };
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: i % 2 === 0 ? 'FFFFFFFF' : 'FFF8FAFC' },
        };
      });

      // Priority color badge
      const priorityCell = row.getCell('priority');
      const priorityColor = this.priorityColor(tc.priority);
      if (priorityColor) {
        priorityCell.font = { bold: true, color: { argb: priorityColor.text } };
        priorityCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: priorityColor.bg },
        };
      }
      priorityCell.alignment = { horizontal: 'center', vertical: 'top' };
      row.height = Math.max(20, Math.ceil(stepsText.split('\n').length * 14));
    }

    // ── Freeze header row ────────────────────────────────────────────────
    sheet.views = [{ state: 'frozen', xSplit: 0, ySplit: 1 }];

    // ── Auto-filter ──────────────────────────────────────────────────────
    sheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: sheet.columns.length },
    };

    // ── Meta sheet ───────────────────────────────────────────────────────
    const meta = workbook.addWorksheet('Meta');
    meta.addRow(['Generated by', 'AI QA Platform']);
    meta.addRow(['Export date', new Date().toISOString()]);
    meta.addRow(['Version', `v${versionNo}`]);
    if (projectName) meta.addRow(['Project', projectName]);
    meta.addRow(['Total test cases', testCases.length]);

    // ── Serialize ────────────────────────────────────────────────────────
    const buffer = Buffer.from(await workbook.xlsx.writeBuffer());
    const fileName = `testcases-v${versionNo}-${Date.now()}.xlsx`;

    this.logger.log(
      `Exported ${testCases.length} test cases → ${fileName} (${buffer.byteLength} bytes)`,
    );

    return { buffer, fileName, sizeBytes: buffer.byteLength };
  }

  private stepsToText(steps: unknown): string {
    if (!Array.isArray(steps)) return String(steps ?? '');
    return steps
      .map((s, i) => {
        const step = s as Record<string, unknown>;
        const no = step.stepNo ?? i + 1;
        const action = step.action ?? '';
        const expected = step.expected ? ` → ${step.expected}` : '';
        return `${no}. ${action}${expected}`;
      })
      .join('\n');
  }

  private refsToText(refs: unknown): string {
    if (Array.isArray(refs)) return refs.join(', ');
    return String(refs ?? '');
  }

  private priorityColor(
    priority: string,
  ): { bg: string; text: string } | null {
    switch (priority?.toUpperCase()) {
      case 'CRITICAL':
        return { bg: 'FFFEE2E2', text: 'FFDC2626' };
      case 'HIGH':
        return { bg: 'FFFFF7ED', text: 'FFEA580C' };
      case 'MEDIUM':
        return { bg: 'FFFFFBEB', text: 'FFD97706' };
      case 'LOW':
        return { bg: 'FFF0FDF4', text: 'FF16A34A' };
      default:
        return null;
    }
  }
}
