"use client"

import React from "react"
import Link from "next/link"
import { AlertTriangle, ChevronRight, Cpu, Moon, User } from "lucide-react"

interface Breadcrumb {
  label: string
  href?: string
}

interface HeaderProps {
  breadcrumbs?: Breadcrumb[]
}

export function Header({ breadcrumbs = [] }: HeaderProps) {
  const isDemoMode = process.env.NEXT_PUBLIC_APP_ACCESS_MODE === "demo"

  return (
    <header className="h-16 border-b border-border bg-card flex items-center justify-between px-8 shrink-0">
      {/* Breadcrumbs */}
      <div className="flex items-center gap-2 text-sm">
        <Link href="/" className="text-muted-foreground hover:text-foreground font-medium transition-colors">
          QAFlow
        </Link>
        {breadcrumbs.map((crumb, index) => (
          <div key={index} className="flex items-center gap-2">
            <ChevronRight className="w-4 h-4 text-muted-foreground/60" />
            {crumb.href ? (
              <Link href={crumb.href} className="text-muted-foreground hover:text-foreground font-medium transition-colors">
                {crumb.label}
              </Link>
            ) : (
              <span className="text-foreground font-semibold">{crumb.label}</span>
            )}
          </div>
        ))}
      </div>

      {/* Utilities */}
      <div className="flex items-center gap-4">
        {isDemoMode ? (
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-amber-500/10 border border-amber-500/30 text-xs text-amber-200 font-semibold max-w-[min(42vw,34rem)]">
            <AlertTriangle className="w-3.5 h-3.5 text-amber-300" />
            <span className="leading-tight">Demo / Mock Mode - AI outputs are simulated and are not generated by a live model.</span>
          </div>
        ) : (
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-secondary border border-border text-xs text-muted-foreground">
            <Cpu className="w-3.5 h-3.5 text-primary" />
            <span>Provider Mode</span>
          </div>
        )}

        {/* Dark Mode Icon */}
        <button className="p-2 rounded-lg hover:bg-secondary text-muted-foreground hover:text-foreground transition-colors">
          <Moon className="w-4.5 h-4.5" />
        </button>

        {/* User Profile */}
        <div className="w-8 h-8 rounded-full bg-secondary flex items-center justify-center border border-border text-muted-foreground cursor-pointer hover:border-primary transition-colors">
          <User className="w-4.5 h-4.5" />
        </div>
      </div>
    </header>
  )
}
